### ISSUE TITLE
41:44: execution error: The variable nil is not defined. (-2753)

### ISSUE THREAD

**Issue by incandescentman** [Lautaro-Garcia/counsel-spotify#1]
I get this error:

`41:44: execution error: The variable nil is not defined. (-2753)`

**Comment by Lautaro-Garcia** [comment]
In which OS are you running Emacs?
What where you trying to do when this error came out?

Thanks for reporting this!

**Comment by incandescentman** [comment]
Mac OSX Sierra version 10.12.5, Spacemacs version 0.200.9, Emacs version 25.1.1, org-mode version 9.0.7.

Here's what I did to get the error (just reproduced):

- M-x package-install counsel-spotify
- (require 'counsel-spotify)
- M-x counsel-spotify-search-track

**Comment by Lautaro-Garcia** [comment]
I'm sorry I don't use Spacemacs anymore, but when I did use it, I didn't have Ivy installed, just Helm. Do you have that dependency? If not and you're effectively using Helm, I would recomend [this package](https://github.com/wandersoncferreira/helm-spotify-plus) that has the same functionality.

**Comment by Lautaro-Garcia** [comment]
I just change a bunch of things in this package to support the new authentication flow of Spotify's Web API. Please check if those changes fixed your issue.

I'm currently using the package in the same Mac OS version that you are using, Emacs 25.2.1, no Spacemacs, just plain Emacs.

**Comment by Lautaro-Garcia** [comment]
No response for over two years, I hope the changes made back then made the package work for you. If you're still using this and have trouble with it, feel free to re-open this issue.
