### ISSUE TITLE
[feature request] Use dbus-call-method instead of shell-command.

### ISSUE THREAD

**Issue by sarg** [Lautaro-Garcia/counsel-spotify#4]
Hi there. Found your package and it's cool!
Looking into the code I've noticed that you make dbus calls with `shell-command dbus-send`. I'm wondering what is the rationale behind that, considering that emacs has dbus support built-in.

Before installing your package I was using https://github.com/remvee/spotify-el, which implements dbus calls with `dbus-call-method`. It works fine.

**Comment by Lautaro-Garcia** [comment]
Wow, I didn't know that! I based my implementation on another [Emacs-spotify](https://github.com/krisajenkins/helm-spotify) integration and they used `shell-command` there.
I will definitely take a look at that, thank you for this info!

**Comment by Lautaro-Garcia** [comment]
I'm going to close this issue now, this package is proudly using `dbus-call-method` for over 5 months now :muscle: Thank you for your suggestion!
