### ISSUE TITLE
Shell command succeded with no output

### ISSUE THREAD

**Issue by Moanrisy** [Lautaro-Garcia/counsel-spotify#5]
After search and press RET, it show "Shell command succeded with not output" and no song played

**Comment by Lautaro-Garcia** [comment]
Ouch, sorry for that. I could use some context information about your system (which OS are you using and what's your emacs version).
It smells like you didn't have Spotify running in the first place, could that be it? I don't remember exactly that behaviour in OSx (I'm running Linux right now) but on Linux, Spotify will not be opened by Emacs. That would be a cool feature though.

Please, try opening first Spotify and then using this package. If that doesn't work either, please send me the info requested above so I can fix this issue.

Have a great day!

**Comment by Moanrisy** [comment]
So i need to run spotify, i thought only emacs needed.
i will try install spotify first then run this package

**Comment by minqhan** [comment]
I'm getting this too on Emacs 26.3 on macOS 10.15.4, with counsel-spotify installed from melpa. When I try to do counsel-spotify-play, it says "(Shell command succeeded with no output)" and nothing happens.
